version: '3.8'

services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: controleAlmoxarifado
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin123
      - POSTGRESQL_DATABASE=almoxarifado
    volumes:
      - postgresql_data:/bitnami/postgresql 

volumes:
  postgresql_data:
    driver: local